### ISSUE TITLE
engine_serialization_core.ts:440 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isMaterial') with Exporter 2.16.0-pre.2

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#38]
Getting this error and black screen in builds with Exporter 2.16.0-pre.2, I can send a repro, just using this starter repro with it on Scene/Basic to repro this though, in Unity 2020.3.38f1

```
engine_serialization_core.ts:440 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isMaterial')
    at deserializeObjectWithType (engine_serialization_core.ts:440:14)
    at tryResolve (engine_serialization_core.ts:287:36)
    at deserializeObject (engine_serialization_core.ts:274:36)
    at handleDeserialization (engine_gltf_builtin_components.ts:194:20)
    at engine_gltf_builtin_components.ts:66:13
    at Module.processNewScripts (engine_mainloop_utils.ts:23:13)
    at Context.internalOnCreate (engine_setup.ts:362:13)
    at async EngineElement.connectedCallback (engine_element.ts:162:17)
```

**Comment by marwie** [comment]
Should be fixed in 2.16.0-pre.3
