### ISSUE TITLE
Exporter 2.16.0-pre.3: Uncaught TypeError: newTarget.getComponentInChildren is not a function

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#39]
Exporter 2.16.0-pre.3, in Unity 2020.3.38f1 - Code that previously worked (unchanged) from Exporter 2.14-pre versions reports that getComponentInChildren is not a function now. I can send a repro project

```
SetCamTarget.ts:22 Uncaught TypeError: newTarget.getComponentInChildren is not a function
    at SetCamTarget.setTarget (SetCamTarget.ts:22:60)
    at invokeFunction (engine_serialization_builtin_serializer.ts:226:33)
    at CallInfo.method (engine_serialization_builtin_serializer.ts:215:57)
    at CallInfo.invoke (EventList.ts:17:14)
    at EventList.invoke (EventList.ts:31:15)
    at Button.onPointerClick (Button.ts:97:23)
    at EventSystem.handleEvents (EventSystem.ts:372:30)
    at EventSystem.handleIntersections (EventSystem.ts:259:22)
    at EventSystem.onBeforeUpdate (EventSystem.ts:180:14)
    at Context.render (engine_setup.ts:437:31)
```

**Comment by marwie** [comment]
Can you console.log ``newTarget`` and send a screenshot?

**Comment by ROBYER1** [comment]
Magically fixed myself after I rotated through prior package versions, will only re-open if it returns

**Comment by marwie** [comment]
What does that mean?
We didnt change ```getComponentInChildren`` in any of the more recent releases. I would suspect the ``newTarget`` is actually not a ``Object3D``

**Comment by ROBYER1** [comment]
The code is correct and always worked before, really not sure what caused the error so I'll keep this closed. No code was changed I just cycled back a few package versions before returning to the latest.
