### ISSUE TITLE
onCollision events not firing

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#58]
Using Exporter 2.21.1-pre

Make a box with a box collider on it, add a box collider to your camera and add the below script to it, move the camera through the cube and see the collision event doesn't fire.

```
import { Behaviour, GameObject } from "@needle-tools/engine/engine-components/Component";

export class CollisionRadius extends Behaviour
{
    onCollision(eventInfo) 
    { 
        console.log(eventInfo); 
    }
}
```

**Comment by ROBYER1** [comment]
Now getting the following warning with 2.22.0-pre exporter, sending over a repro project now as I can't find a way to fix it

```
TypeError: trigger.raiseOnEnterEvent is not a function
    at SpatialTriggerReceiver.onEnterTrigger (SpatialTrigger.ts:65:17)
    at Component.ts:582:17
    at GameObject.foreachComponent (Component.ts:106:33)
    at GameObject.invoke (Component.ts:577:14)
    at _SpatialTrigger.raiseOnEnterEvent (SpatialTrigger.ts:114:20)
    at 
```

**Comment by marwie** [comment]
Will be fixed in next update
