### ISSUE TITLE
Animation setting gameobject with Canvas as Child error: Cannot read properties of null (reading 'x') at SingleUniform.setValueV3f [as setValue]

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#88]
Unity 2022.1.16f1, Exporter 2.32.0-pre, Windows 11

Using newer versions to test out animations that open/close UI, I have hotspots that call a script to open a 3d panel model. On that panel model is an animation made in Unity that sets active on/off a gameobject underneath it which has a Canvas as the child. It produces this error.

The same issue doesn't happen when in code I programmatically make that gameobject active/inactive, only affects animation

Repro sent via wetransfer with this github issue title in name

Error from Chrome console:
```
Uncaught TypeError: Cannot read properties of null (reading 'x')
    at SingleUniform.setValueV3f [as setValue] (three.module.js:17175:9)
    at WebGLUniforms.upload (three.module.js:17997:7)
    at setProgram (three.module.js:28320:18)
    at WebGLRenderer.renderBufferDirect (three.module.js:27240:19)
    at renderObject (three.module.js:27870:10)
    at renderObjects (three.module.js:27839:5)
    at renderScene (three.module.js:27763:40)
    at WebGLRenderer.render (three.module.js:27581:4)
    at Context.render (engine_setup.ts:564:19)
    at onAnimationFrame (three.module.js:27454:35)
```

**Comment by ROBYER1** [comment]
Seems to happen with animations that have morph targets in them, and only happens until a clean install happens before the next time we update Needle Exporter.

Once Needle Exporter has updated (e.g. to Exporter 2.36.0-pre), the builds have loads more errors until we run a Full Export & Play and a Clean Install then after to get around the issue `Uncaught TypeError: Cannot read properties of null (reading 'x')` once again

**Comment by marwie** [comment]
Should be fixed in the next version
